[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "2qtD2meLckv1sYRU6Hv36SFL1bVc3VPK3FvGPpf97X7E"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/alfred/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
