[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "7nZERk2LZF1bJDQzV4H2VaoYxLQ5uivr7xagMVvsuQ8X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/alfred/.config/solana/devnet.json"

[scripts]
test = "node tests/myepicproject.js"
